Sprint2
ClevertecFrontendLab/sprint2-byshlata pull request #1
Opened 2023-02-08 20:23 UTC by byshlata

2023-02-08 20:27 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675888023/slider%20one%20foto%20768px.png)

2023-02-08 20:33 UTC, klichkovskiy requested changes

2023-02-08 20:33 UTC, klichkovskiy commented on src/components/menu/menu-mini/menu-mini.tsx
> +        <MenuMiniContainer data-test-id='burger-navigation'>
![image](https://user-images.githubusercontent.com/62481116/217644306-7acaf853-f805-41c0-9c45-bcd81a33d677.png)
При клике вне данной области адаптивное меню должно закрыться

2023-02-08 20:33 UTC, klichkovskiy commented on src/components/menu/menu-mini/menu-mini.tsx
> +        <MenuMiniContainer data-test-id='burger-navigation'>
![image](https://user-images.githubusercontent.com/62481116/217644497-c305ca42-b043-4327-88d5-94cab73a8af9.png)
Должно быть свернуто если находишься где-то кроме страницы с книгами

2023-02-08 21:05 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 10%.
Общее количество тестов: 10.
Количество непройденных тестов: 9.
***
**Test width 1440px -- test button comment view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675890355/Test%20width%201440px%20--%20test%20button%20comment%20view%20(failed).png)
***
**Test width 1440px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675890355/Test%20width%201440px%20--%20test%20navigation%20view%20(failed).png)
***
**Test width 1440px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675890355/Test%20width%201440px%20--%20test%20slider%20(failed).png)
***
**Test width 320px -- test layout burger-menu (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675890355/Test%20width%20320px%20--%20test%20layout%20burger-menu%20(failed).png)
***
**Test width 320px -- test search (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675890355/Test%20width%20320px%20--%20test%20search%20(failed).png)
***
**Test width 320px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675890355/Test%20width%20320px%20--%20test%20slider%20(failed).png)
***
**Test width 768px -- test layout burger-menu (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675890355/Test%20width%20768px%20--%20test%20layout%20burger-menu%20(failed).png)
***
**Test width 768px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675890355/Test%20width%20768px%20--%20test%20navigation%20view%20(failed).png)
***
**Test width 768px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675890355/Test%20width%20768px%20--%20test%20slider%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675890355/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675890355/app%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675890355/app.png)

2023-02-08 23:15 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 10.
Количество непройденных тестов: 2.
***
**Test width 1440px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/Test%20width%201440px%20--%20test%20navigation%20view%20(failed).png)
***
**Test width 768px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/Test%20width%20768px%20--%20test%20navigation%20view%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/byshlata/1675898148/slider%20one%20foto%20768px.png)

2023-02-09 08:26 UTC, klichkovskiy approved these changes
Удачи на 3 спринте!

2023-02-09 08:28 UTC, merged